version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: codedeploy/Dockerfile

    ports:
      - '3000:3000'

    env_file:
      - .env

    volumes:
      - "./storage/static:/app/storage/static"

    networks:
      - web

  storage:
    build:
      context: storage/
      dockerfile: Dockerfile

    ports:
      - '8000:8000'

    env_file:
      - .env

    volumes:
      - "./storage/static:/app/static"

    networks:
      - web

  db:
    image: postgres:14.2-alpine
    restart: unless-stopped
    container_name: db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - web


    env_file:
      - .env

    expose:
      - 5432
    ports:
      - "5432:5432"

networks:
  web:
    external: true
