version: '3.3'

services:
  web:

    image: node:16

    command: npm run dev

    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app

    env_file:
      - .env

    ports:
      - "3000:3000"

    networks:
      - backend

    environment:
      VIRTUAL_HOST: next-store.local
      HOST: 0.0.0.0

  nginx-proxy:
    build:
      context: codedeploy/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "./storage/public:/var/www/html/public:delegated"

    networks:
      - web
      - backend

  db:
    image: postgres:14.2-alpine
    restart: unless-stopped
    container_name: db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - backend


    env_file:
      - .env

    ports:
      - "5432:5432"

networks:
  web:
    external: true
  backend:
    driver: bridge
