version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: codedeploy/Dockerfile

    ports:
      - '3000:3000'

    env_file:
      - .env.local

    networks:
      - web

networks:
  web:
    external: true
